#!/usr/bin/env python3
"""Profile builder: word-frequency lists -> bigram log-prob tables.

Input: en_50k.txt / ru_50k.txt next to this script, downloaded from
https://github.com/hermitdave/FrequencyWords (OpenSubtitles-derived word
lists; content is CC-BY-SA 4.0, see ATTRIBUTION.md next to this script).

Method: for each word with frequency f, count boundary-aware bigrams
(^,c1),(c1,c2),...,(cn,^) weighted by f, then add-k smoothed log P(b|a).
Cross-word pairs are approximated through the shared boundary symbol.

Regenerate: place both lists beside this script and run
`python3 gen_profiles.py` from this directory. Output is deterministic
(fixed float formatting, fixed symbol order); it rewrites tables.rs.
"""

import math
from pathlib import Path

EN_ALPHA = "abcdefghijklmnopqrstuvwxyz"
RU_ALPHA = "абвгдежзийклмнопрстуфхцчшщъыьэюяё"
K = 0.5
HERE = Path(__file__).resolve().parent


def load(path, alpha):
    counts = {}
    totals = {}
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            parts = line.split()
            if len(parts) != 2:
                continue
            word, freq = parts[0].lower(), float(parts[1])
            if not word or any(c not in alpha for c in word):
                continue
            seq = ["^"] + list(word) + ["^"]
            for a, b in zip(seq, seq[1:]):
                counts[(a, b)] = counts.get((a, b), 0.0) + freq
                totals[a] = totals.get(a, 0.0) + freq
    return counts, totals


def emit(name, alpha, counts, totals, out):
    symbols = ["^"] + list(alpha)
    v = len(symbols)
    table = []
    for a in symbols:
        for b in symbols:
            p = (counts.get((a, b), 0.0) + K) / (totals.get(a, 0.0) + K * v)
            table.append(f"{math.log(p):.4f}")
    out.write(f'pub const {name}_SYMBOLS: &str = "^{alpha}";\n')
    out.write(f"pub const {name}: [f32; {v * v}] = [\n")
    for i in range(0, len(table), 8):
        out.write("    " + ", ".join(table[i : i + 8]) + ",\n")
    out.write("];\n")
    out.write(f"pub const {name}_N: usize = {v};\n")


def main():
    en_counts, en_totals = load(HERE / "en_50k.txt", EN_ALPHA)
    ru_counts, ru_totals = load(HERE / "ru_50k.txt", RU_ALPHA)
    with open(HERE / "tables.rs", "w", encoding="utf-8") as out:
        out.write(
            "// Generated by src/scorer/gen_profiles.py from FrequencyWords\n"
            "// word lists (see ATTRIBUTION.md). Do not edit by hand.\n"
        )
        emit("EN", EN_ALPHA, en_counts, en_totals, out)
        emit("RU", RU_ALPHA, ru_counts, ru_totals, out)
    print(f"en bigrams: {len(en_counts)}, ru bigrams: {len(ru_counts)}")


main()
